# Generated by Django 4.2.1 on 2023-05-30 20:27

from django.db import migrations, models
import django.db.models.deletion
import galeria.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('marca', models.CharField(choices=[('HONDA', 'Honda'), ('YAMAHA', 'Yamaha'), ('BMW', 'BMW'), ('AUDI', 'Audi'), ('FIAT', 'Fiat'), ('CHEVROLET', 'Chevrolet'), ('VOLVO', 'Volvo'), ('IVECO', 'Iveco'), ('DUCATI', 'Ducati'), ('HYUNDAI', 'Hyundai'), ('TRIUMPH', 'Triumph')], default='', max_length=30)),
                ('ano', models.CharField(max_length=12)),
                ('km', models.FloatField()),
                ('valor', models.FloatField()),
                ('tipo', models.CharField(choices=[('MOTO', 'Moto'), ('CARRO', 'Carro'), ('VANS', 'Vans'), ('CAMINHOES', 'Caminhoes')], default='', max_length=30)),
                ('legenda', models.TextField(max_length=80)),
                ('publicada', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to=galeria.models.upload_to)),
                ('veiculo', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='galeria.veiculo')),
            ],
        ),
    ]
