# Generated by Django 4.2.1 on 2023-06-17 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculo',
            name='cambio',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='combustivel',
            field=models.CharField(choices=[('GASOLINA', 'Gasolina'), ('ÁLCOOL', 'Álcool'), ('DIESEL', 'Diesel'), ('ELÉTRICO', 'Elétrico'), ('HÍBRIDO', 'Híbrido')], default='', max_length=30),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='cor',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='motor',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='veiculo',
            name='portas',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
