# Generated by Django 4.2.1 on 2023-06-17 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0002_veiculo_cambio_veiculo_combustivel_veiculo_cor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='motor',
            field=models.CharField(max_length=20),
        ),
    ]
