# Generated by Django 4.2.1 on 2023-08-16 01:03

from django.db import migrations, models
import galeria.models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0005_alter_veiculo_marca'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=20)),
                ('logo', models.FileField(blank=True, default='', upload_to=galeria.models.upload_too)),
            ],
        ),
    ]
