# Generated by Django 4.2.1 on 2023-08-16 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0006_marca'),
    ]

    operations = [
        migrations.AddField(
            model_name='marca',
            name='tipo',
            field=models.CharField(choices=[('MOTO', 'Moto'), ('CARRO', 'Carro'), ('VANS', 'Vans'), ('CAMINHOES', 'Caminhoes')], default='', max_length=30),
        ),
    ]
