# Generated by Django 4.2.1 on 2023-08-16 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0007_marca_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='marca',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='marcas', to='galeria.marca'),
        ),
    ]
