# Generated by Django 4.2.1 on 2023-08-16 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0010_alter_veiculo_marca'),
    ]

    operations = [
        migrations.AddField(
            model_name='foto',
            name='posicao',
            field=models.CharField(default='', max_length=3),
        ),
    ]
