# Generated by Django 4.2.1 on 2023-08-17 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0016_rename_usuario_veiculo_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='veiculo',
            name='user',
        ),
    ]
