# Generated by Django 4.2.2 on 2023-08-18 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0018_veiculo_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='veiculo',
            name='cambio',
        ),
        migrations.RemoveField(
            model_name='veiculo',
            name='portas',
        ),
        migrations.AddField(
            model_name='veiculo',
            name='câmbio',
            field=models.CharField(choices=[('MANUAL', 'MANUAL'), ('AUTOMATIZADO', 'AUTOMATIZADO'), ('AUTOMÁTICO', 'AUTOMÁTICO'), ('CVT', 'CVT')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='combustivel',
            field=models.CharField(choices=[('GASOLINA', 'GASOLINA'), ('ÁLCOOL', 'ÁLCOOL'), ('DIESEL', 'DIESEL'), ('ELÉTRICO', 'ELÉTRICO'), ('HÍBRIDO', 'HÍBRIDO'), ('GASOLINA E ÁLCOOL', 'GASOLINA E ÁLCOOL')], default='', max_length=30),
        ),
    ]
