# Generated by Django 4.2.2 on 2023-08-30 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0019_remove_veiculo_cambio_remove_veiculo_portas_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foto',
            name='imagem',
        ),
    ]
