# Generated by Django 4.2.2 on 2023-08-30 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0020_remove_foto_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='foto',
            name='image',
            field=models.ImageField(default=None, upload_to='images'),
        ),
    ]
