# Generated by Django 4.2.2 on 2023-08-30 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0021_foto_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foto',
            old_name='image',
            new_name='imagem',
        ),
    ]
