# Generated by Django 4.2.2 on 2023-08-30 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0022_rename_image_foto_imagem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marca',
            name='logo',
        ),
    ]
