# Generated by Django 4.2.2 on 2023-08-30 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0024_marca_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marca',
            name='logo',
        ),
    ]
